apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lxde5q0mv-java-springboot
  janus-idp.io/tekton: lxde5q0mv-java-springboot
  backstage.io/kubernetes-id: lxde5q0mv-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lxde5q0mv-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
